### ISSUE TITLE
The server module seems to be commented out...?

### ISSUE THREAD

**Issue by AnsonSavage** [Student-Accomplice-Pipeline-Team/accomplice_pipe#16]
![image](https://github.com/Student-Accomplice-Pipeline-Team/accomplice_pipe/assets/12112399/f0198d8d-c4db-417f-9e1c-81ec92bee0f9)

(This is in the production branch)

![image](https://github.com/Student-Accomplice-Pipeline-Team/accomplice_pipe/assets/12112399/9043fccf-e76d-4910-97e0-c5af74936df4)

**Comment by maminson** [comment]
This is `pipe.shared.server`, not `pipe.server` which is [a variable in `pipe`'s `__init.py__` file](https://github.com/Student-Accomplice-Pipeline-Team/accomplice_pipe/blob/2e494f52bd5c986e4157d625fca0cda3e336ae21/pipe/accomplice/software/houdini/pipe/__init__.py#L13). `pipe.shared.server` was created then rapidly deprecated as the pipeline structure was refactored and changed during construction.
