### ISSUE TITLE
Geo Variant Node needs to define a subdivision scheme attribute.

### ISSUE THREAD

**Issue by looop45** [Student-Accomplice-Pipeline-Team/accomplice_pipe#9]
When testing laying out assets as instances, you can't set a subdivision scheme on instanced meshes. It needs to be set beforehand.

As an aside, some of the leftover nodes in the geovariant node should be removed as they are based on older versions of HDAs and have funky wunky behavior. 

I'm probably going to immediately fix this myself buuuuuuuut thought I should track it.

**Comment by maminson** [comment]
Is this still an issue?

**Comment by looop45** [comment]
Yeah I fixed this lol.
